[package]
name = "routrie"
version = "0.6.0"
edition = "2021"
description = "Rust port of the Python stdlib routrie modules"
readme = "README.md"
license-file = "LICENSE.txt"

[lib]
name = "routrie"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "^0.16.0"
features = ["extension-module", "abi3-py37"]

[dependencies]
path-tree = "^0.4.0"

[package.metadata.maturin]
python-source = "python"
description-content-type = "text/markdown; charset=UTF-8; variant=GFM"
name = "routrie._routrie"
